### ISSUE TITLE
Amount of amendments and scroll bar

### ISSUE THREAD

**Issue by Socioneers** [kgish/discourse-annotator-plugin#123]
Visualise the amount of amendments in sidebar

And let scrollbar always visible so that it is obvious that people need to scroll down to see other amendments.

**Comment by Socioneers** [comment]
<img width="514" alt="screen shot 2016-12-14 at 13 30 43" src="https://cloud.githubusercontent.com/assets/11832800/21182334/cdd5a4d8-c202-11e6-9cba-3b394e7b1723.png">

**Comment by kgish** [comment]
What do you mean 'scrollbar always visible' ? I believe that if the contents flow below the bottom edge that the scrollbar appears anyway.

**Comment by Socioneers** [comment]
Scroll bar only appears when you make a scroll movement. A lot of users don’t know there are more amendments lower in the sidebar. To have the scroll bar permanent visible will help suggesting there is more to see.

**Comment by kgish** [comment]
Oh is that so? Maybe browser differences. Will take of it!

**Comment by kgish** [comment]
The real mccoy.
![screenshot from 2016-12-14 22-27-13](https://cloud.githubusercontent.com/assets/79195/21201827/b1bf2bf8-c24c-11e6-8387-01a1b0ada985.png)

**Comment by kgish** [comment]
I'd like to propose the following:

Each amendment will be preceded by the `annotation_id` and at the top just under the caption there will appear a button group for all of the amendments, allowing the user to click on a given button in order to scroll down to the chosen one.

```
x 5 Amendementen
[123] [133] [167] [33] ...
```

Of course, if there's just one amendment, then this is not needed.

**Comment by kgish** [comment]
This is what I did in order to make things more user-friendly, tell me what you think.

Hovering over navigation button.
![screenshot from 2016-12-15 15-27-55](https://cloud.githubusercontent.com/assets/79195/21228315/a036cbc0-c2dd-11e6-922b-50e9bfde5502.png)

After clicking.
![screenshot from 2016-12-15 15-28-27](https://cloud.githubusercontent.com/assets/79195/21228316/a036e916-c2dd-11e6-9653-a56655823d18.png)

**Comment by Socioneers** [comment]
Looks good but maybe to far fetched, I will discus this tonight. When you can do this could you direct the annotation deel link directly to the annotation so that you don’t have to scroll?

Cheers,

**Comment by kgish** [comment]
No problem, if too far-fetched am happy to disable it. Just a flits of the imagination that I wanted to tickle your fancy.

May a variation on the theme might come up during the demo.

Yes, now the `deel` link scrolls down automatically for your pleasure.

Will update the test server so you can have a look.
