### ISSUE TITLE
Permissions: remove reaction possibility for user while topics are being annotated

### ISSUE THREAD

**Issue by Socioneers** [kgish/discourse-annotator-plugin#58]
users should not be able to leave a reaction under the motie text

**Comment by kgish** [comment]
Do not understand, please explain and/or include a screenshot illustrating what you mean.

**Comment by Socioneers** [comment]
Sorry. During amendments users are not allowed to reply/ give reactions on a topic (eg election draft). Users are only allowed to react on a topic with an amendment.

**Comment by kgish** [comment]
Still not sure I understand this. Are you saying that I should hide the [Reageer]-button for all moties?

Wow, that's pretty much most of what Discourse does, reply threads, and you want to disable that?

Seems that this whole annotator thing is becoming a rewrite for reply. Does the PvdA understand what Discourse is? 

I hope I'm misunderstanding this?

**Comment by Socioneers** [comment]
Hide [Reageer]-button for all text that will be **amended** with the annotator. In the amendment period users are only allowed to react by amendments on the text (15/10-15/11) the election program. If people would react also under the text (with questions and opinions) it will become confusing and interfere with the process (written in there statutes).

**Comment by Socioneers** [comment]
Reageer button is still there, while during test 6/10 it was not there.

<img width="899" alt="screen shot 2016-10-10 at 10 59 06" src="https://cloud.githubusercontent.com/assets/11832800/19231163/c68bf8a6-8ed8-11e6-9767-463d4a441c02.png">

**Comment by Socioneers** [comment]
Remove "nieuw onderwerp" in share popup > are related
https://github.com/kgish/discourse-pvda-plugin/issues/33

**Comment by kgish** [comment]
Isn't related to the annotatorjs library, but if you want to create an issue here so that you can track things better that's fine with me.

Purposely separated pvda-specific items from those related to the annotator library, so that we could retain a nicely isolated annotator building-block which could easily be used for other customers with their own wishes.

**Comment by kgish** [comment]
I am not sure if I will have enough time to do this before my vacation, will do my best. If worse comes to worse I will try and spend some time on it while abroad.

**Comment by kgish** [comment]
Added a new setting in the admin dashboard plugins:

![deel-een-link-admin-setting](https://cloud.githubusercontent.com/assets/79195/19408680/8d76c566-92c3-11e6-9429-72bd42ceb065.png)

So that when this checkbox is selected (enabled) the popup has the [Nieuwe onderwerp]-link hidden:
![deel-een-link](https://cloud.githubusercontent.com/assets/79195/19408693/eed97e84-92c3-11e6-9cec-cef80d0b4a83.png)

**Comment by kgish** [comment]
Updated test server with this fix.

**Comment by Socioneers** [comment]
On test I see that it works with the newer category, the older categories have still the reageer button.

**Comment by kgish** [comment]
You will need to update the annotator- and/or pvda- categories list in the admin dashboard in order to get this working.

Will leave it up to you as a learning experience, please retry and tell me how it goes.

**Comment by kgish** [comment]
Tried on the test server using your links, and according to me they both work just fine.

Moved back to 'waiting for test' column.
