### ISSUE TITLE
Auto-refresh: annotations turn up slow and after manual refresh

### ISSUE THREAD

**Issue by Socioneers** [kgish/discourse-annotator-plugin#71]
Could we do something like this?
http://stackoverflow.com/questions/4644027/how-to-automatically-reload-a-page-after-a-given-period-of-inactivity

**Comment by kgish** [comment]
Yes that's possible. Very clever solution by the way. However, I believe that Discourse already does something like that or not?

Not sure what the implications might be for the user when an unexpected refresh occurs.

The easiest option would be to add an admin setting where the timeout in seconds could be indicated.

Would you like me to do that?

**Comment by Socioneers** [comment]
What is the less time consuming option?

**Comment by Socioneers** [comment]
The easiest option would be to add an admin setting where the timeout in seconds could be indicated.
>I like easy options

**Comment by kgish** [comment]
Will do.

**Comment by kgish** [comment]
Should this be enabled by default? If yes, what should the value be in seconds?

**Comment by Socioneers** [comment]
Should this be enabled by default? If yes, what should the value be in seconds? > I would say 0,15 second

Just for the amendment page or all pages>  is not necessary on the other pages

**Comment by kgish** [comment]
0,15 second? We're talking about refreshing the **whole** page here. I was thinking more like once every 5 minutes or such.

**Comment by Socioneers** [comment]
The problem is that people are not seeing their input if they not refresh or other peoples input. Will it have to much input on the system to do it more frequently?

**Comment by kgish** [comment]
I see. The link you provided in this issue refers to an inactivity timer refreshing the whole page which is a different ballgame. Guess that's why I was on the wrong track.

So you want this to be "real-time" environment with everyone seeing the latest state of all annotations by accessing the database for every single change.

That's another story and requires a major rethink/rehaul on the whole architecture.

Would this be a websockets kind of thing or ajax calls in the background, neither are ideal.

This would more than likely pull down the server, requiring a much more powerful system.

Would recommend not considering this route, or parking it for the time being.

**Comment by Socioneers** [comment]
Related?
https://github.com/discourse/discourse/commit/f87fc98411e35f0d44a0a2076a30fb509ce0f804

**Comment by kgish** [comment]
Don't thing so. Was fixed more than a year ago, so if it was related the problem shouldn't appear.
